### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Meddy24** [marthaluka/TidyTuesday#1]
Hey , every time i run this line

africa_geom <- world %>%                                     
  mutate(across(where(is.character),str_trim))

 it returns this error.
Error in mutate(., across(where(is.character), str_trim)) : 
  object 'world' not found

i installed and loaded the sf package

**Comment by marthaluka** [comment]
Please ensure that the package "**spData**" is installed and loaded. The _world_ dataframe is located within the package. You can do this using `pacman` as in the beginning of the script or `install.packages("spData")`, then `library("spData")`.

**Comment by marthaluka** [comment]
Please ensure that the package "**spData**" is installed and loaded. The **world** dataframe is located within the package. You can do this using `pacman` as in the beginning of the script or `install.packages("spData")`, then `library("spData")`.
